//==================================================================================================
// This is the Jenkins pipeline script for building the OMAR GIT Mirror application.
// Environment varialbes that MUST be passed in by Jenkins:
//    OSSIM_GIT_BRANCH: The tag of the branch to be built. Typically dev or master.
//
// Environment varaibles that MUST be set in the Jenkins global environment (manage jenkins -> configure system -> environment varaibles)
//    REPOSITORY_MANAGER_USER: The user to use when pushing artifacts
//    REPOSITORY_MANAGER_PASSWORD: The password to use when pushing artifacts
//    OPENSHIFT_USERNAME: The user to use logging into the docker registry
//    OPENSHIFT_PASSWORD: The password to use logging into the docker registry
//==================================================================================================

def notifyObj
node ("ossim-build") {
    env.WORKSPACE = pwd()
    def appName = "ossim-csm-plugin"
    env.MAKE_VERBOSE = "${ MAKE_VERBOSE }"
    env.OSSIM_INSTALL_PREFIX = "${ env.WORKSPACE }/ossim"
    env.MSP_INSTALL_DIR = "/usr/local/msp-1.5"
    env.MSP_HOME = "/usr/local/msp-1.5"
    env.CSM_HOME = "/usr/local/csm"
    try {
        stage( "Checkout" ) {
            dir( "ossim-csm-plugin" ) {
                git branch: "${ OSSIM_GIT_BRANCH }", url: "${GIT_PUBLIC_SERVER_URL}/ossim-csm-plugin.git"
            }
        }

        echo "WORKSPACE: ${ env.WORKSPACE }"

        stage( "Download Artifacts" ) {
            dir( "${ env.WORKSPACE }" ) {
               step ([$class: "CopyArtifact",
                      projectName: "ossim-ci-${OSSIM_GIT_BRANCH}",
                      filter: "ossim-ci-${OSSIM_GIT_BRANCH}.tgz",
                      flatten: true])
               sh "tar xvfz ossim-ci-${OSSIM_GIT_BRANCH}.tgz"
               notifyObj = load "${env.WORKSPACE}/ossim-ci/jenkins/pipeline/notify.groovy"
               step ([ $class: "CopyArtifact",
                    projectName: "ossim-${ OSSIM_GIT_BRANCH }",
                    filter: "artifacts/ossim-install.tgz",
                    flatten: true ])
            }
        }

        stage( "Build" ) {
            sh """
                echo "WORKSPACE            = ${env.WORKSPACE}"
                echo "OSSIM_INSTALL_PREFIX = ${env.OSSIM_INSTALL_PREFIX}"
                mkdir -p ${ env.OSSIM_INSTALL_PREFIX }
                tar xfz ossim-install.tgz -C ${ env.OSSIM_INSTALL_PREFIX }
                mv ${ env.OSSIM_INSTALL_PREFIX }/install/* ${ env.OSSIM_INSTALL_PREFIX }
                 
                rm -rf ${ env.WORKSPACE }/build/CMakeCache.txt
                ${ env.WORKSPACE }/ossim-csm-plugin/scripts/buildNative.sh
            """
        }

        stage("Archive"){
            dir("${env.WORKSPACE}/ossim-csm-plugin") {
               sh "tar cvfz ossim-csm-plugin-install.tgz install"
               archiveArtifacts artifacts:"*.tgz"
            }
       }
       stage("Deliver Artifacts"){
            dir("${env.WORKSPACE}/ossim-csm-plugin"){

              step([$class: 'S3BucketPublisher',
                    dontWaitForConcurrentBuildCompletion: false,
                    entries: [
                               [bucket: "o2-delivery/${OSSIM_GIT_BRANCH}/ossim",
                               excludedFile: '',
                               flatten: false,
                               gzipFiles: false,
                               keepForever: false,
                               managedArtifacts: false,
                               noUploadOnFailure: false,
                               selectedRegion: 'us-east-1',
                               showDirectlyInBrowser: true,
                               sourceFile: "*.tgz",
                               storageClass: 'STANDARD',
                               uploadFromSlave: false,
                               useServerSideEncryption: false]],

                    profileName: 'o2-cicd',
                    userMetadata: []])
            }
       }
    }

    catch( e ) {
        println "ERROR: ${e} "
        currentBuild.result = "FAILED"
        notifyObj?.notifyFailed()
    }
try {
        stage('SonarQube analysis') {
            withSonarQubeEnv('sonar_cloud') {
                // requires SonarQube Scanner for Gradle 2.1+
                // It's important to add --info because of SONARJNKNS-281
                sh """
                  pushd ${env.WORKSPACE}/${appName}/
                  sonar-scanner
                  popd
                """
            }
        }
    }
    catch (e) {
        echo e.toString()
    }
    stage( "Clean Workspace" ) {
        step([ $class: 'WsCleanup' ])
    }
}
